title: Verv
description: Handpicked stories, jokes, and creative writing.
baseurl: ""
url: "https://rish-man.github.io/verv.reads"

markdown: kramdown

collections:
  stories:
    output: true
  jokes:
    output: false
  songs:
    output: false
